FROM oven/bun:canary-alpine

WORKDIR /app

COPY backend/package.json backend/package.json ./

RUN bun install --frozen-lockfile

COPY backend/ .

RUN bunx prisma generate 

EXPOSE 3000

ENV BUN_ENV=production
ENV PORT=3000

CMD ["bun", "run", "start"]
