
// OPENROUTER
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || "dd";

//POSTMARK
const POSTMARK_SERVER_TOKEN = process.env.POSTMARK_SERVER_TOKEN  
const FROM_EMAIL = process.env.FROM_EMAIL  

//OTHER
const PORT = process.env.PORT || 3000;
const NODE_ENV = process.env.NODE_ENV  
const JWT_SECRET = process.env.JWT_SECRET || "klfkdsj"

//DB
const DATABASE_URL = process.env.DATABASE_URL  

// Razorpay
const RAZORPAY_KEY_ID = process.env.RAZORPAY_KEY_ID  
const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET  
const RAZORPAY_PLAN_ID = process.env.RAZORPAY_PLAN_ID  
const RAZORPAY_ENVIRONMENT = process.env.RAZORPAY_ENVIRONMENT 

//FRONTEND 
const FRONTEND_URL = process.env.FRONTEND_URL  

export { 
    PORT, 
    JWT_SECRET,
    NODE_ENV,
    OPENROUTER_API_KEY ,
    POSTMARK_SERVER_TOKEN,
    FROM_EMAIL,
    DATABASE_URL,
    RAZORPAY_KEY_ID,
    RAZORPAY_KEY_SECRET,
    RAZORPAY_PLAN_ID,
    RAZORPAY_ENVIRONMENT,
    FRONTEND_URL
};